import { SEO } from '../../components/SEO';
import React, { useState } from 'react';
import { Copy, CheckCircle2 } from 'lucide-react';
import { ToolDescription } from '../../components/ToolDescription';
import { toolDescriptions } from '../../data/toolDescriptions';

export function HtaccessGenerator() {
  const [www, setWww] = useState('none');
  const [https, setHttps] = useState(false);
  const [customError, setCustomError] = useState(false);
  const [copied, setCopied] = useState(false);

  const generateHtaccess = () => {
    let code = `# Generated by OptiSEO\n\n`;
    
    if (www !== 'none' || https) {
      code += `<IfModule mod_rewrite.c>\nRewriteEngine On\n\n`;
      
      if (www === 'force') {
        code += `# Force WWW\nRewriteCond %{HTTP_HOST} !^www\. [NC]\nRewriteRule ^(.*)$ http://www.%{HTTP_HOST}/$1 [R=301,L]\n\n`;
      } else if (www === 'remove') {
        code += `# Remove WWW\nRewriteCond %{HTTP_HOST} ^www\.(.*)$ [NC]\nRewriteRule ^(.*)$ http://%1/$1 [R=301,L]\n\n`;
      }
      
      if (https) {
        code += `# Force HTTPS\nRewriteCond %{HTTPS} off\nRewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]\n\n`;
      }
      
      code += `</IfModule>\n\n`;
    }
    
    if (customError) {
      code += `# Custom Error Pages\nErrorDocument 400 /400.html\nErrorDocument 401 /401.html\nErrorDocument 403 /403.html\nErrorDocument 404 /404.html\nErrorDocument 500 /500.html\n\n`;
    }
    
    return code;
  };

  const code = generateHtaccess();

  const handleCopy = () => {
    if (code) {
      navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <>
      <SEO title=".htaccess Generator - OptiSEO Tools" description="Generate common .htaccess rules for your Apache server." />
      <div className="container mx-auto px-4 py-12">
      <div className="max-w-4xl mx-auto">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-4">.htaccess Generator</h1>
          <p className="text-gray-600 dark:text-gray-400">Generate common .htaccess rules for your Apache server.</p>
        </div>
        <div className="bg-white dark:bg-gray-900 p-6 rounded-2xl border border-gray-200 dark:border-gray-800 shadow-sm">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
            <div>
              <h3 className="text-lg font-medium text-gray-900 dark:text-white mb-4">WWW Redirect</h3>
              <div className="space-y-2">
                <label className="flex items-center gap-2 text-gray-700 dark:text-gray-300">
                  <input type="radio" name="www" value="none" checked={www === 'none'} onChange={() => setWww('none')} className="text-[#4f39f6] focus:ring-[#4f39f6]" />
                  Do not change
                </label>
                <label className="flex items-center gap-2 text-gray-700 dark:text-gray-300">
                  <input type="radio" name="www" value="force" checked={www === 'force'} onChange={() => setWww('force')} className="text-[#4f39f6] focus:ring-[#4f39f6]" />
                  Force www.
                </label>
                <label className="flex items-center gap-2 text-gray-700 dark:text-gray-300">
                  <input type="radio" name="www" value="remove" checked={www === 'remove'} onChange={() => setWww('remove')} className="text-[#4f39f6] focus:ring-[#4f39f6]" />
                  Remove www.
                </label>
              </div>
            </div>
            <div>
              <h3 className="text-lg font-medium text-gray-900 dark:text-white mb-4">Other Options</h3>
              <div className="space-y-2">
                <label className="flex items-center gap-2 text-gray-700 dark:text-gray-300">
                  <input type="checkbox" checked={https} onChange={(e) => setHttps(e.target.checked)} className="text-[#4f39f6] focus:ring-[#4f39f6] rounded" />
                  Force HTTPS
                </label>
                <label className="flex items-center gap-2 text-gray-700 dark:text-gray-300">
                  <input type="checkbox" checked={customError} onChange={(e) => setCustomError(e.target.checked)} className="text-[#4f39f6] focus:ring-[#4f39f6] rounded" />
                  Custom Error Pages
                </label>
              </div>
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Generated .htaccess</label>
            <div className="relative">
              <textarea
                className="w-full h-64 p-4 pr-12 border border-gray-300 dark:border-gray-700 rounded-xl bg-gray-50 dark:bg-gray-800 text-gray-900 dark:text-white resize-none font-mono text-sm whitespace-pre"
                readOnly
                value={code}
              ></textarea>
              <button 
                onClick={handleCopy}
                className="absolute right-4 top-4 text-gray-400 hover:text-[#4f39f6] dark:hover:text-[#4f39f6] transition-colors"
              >
                {copied ? <CheckCircle2 className="w-5 h-5 text-green-500" /> : <Copy className="w-5 h-5" />}
              </button>
            </div>
          </div>
        </div>
      </div>
      <ToolDescription points={toolDescriptions['htaccess-generator']} />
    </div>
    </>
  );
}
